_BASE_: "../Base-RCNN.yaml"
MODEL:
  WEIGHTS: "/Path/to/ImageNet/Pretrain/Weight"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
  ROI_HEADS:
    NUM_CLASSES: 7
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.75
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('4ch_trainval_base1', )
  TEST: ('4ch_test_base1',)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  STEPS: (20000, 26600)
  MAX_ITER: 5000
  CHECKPOINT_PERIOD: 200000
  WARMUP_ITERS: 100
OUTPUT_DIR: "/Path/to/Output/Dir"