_BASE_: "../Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "/Path/to/ImageNet/Pretrain/Weight"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
  ROI_HEADS:
    NUM_CLASSES: 4
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.75
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('3vt_trainval_base3', )
  TEST: ('3vt_test_base3',)
SOLVER:
  STEPS: (10000, 13300)
  MAX_ITER: 15000
  CHECKPOINT_PERIOD: 200000
  WARMUP_ITERS: 100
OUTPUT_DIR: "/Path/to/Output/Dir"