_BASE_: "../../Base-RCNN.yaml"
MODEL:
  WEIGHTS: "/Path/to/ImageNet/Pretrain/Weight"
  MASK_ON: False
  BACKBONE:
    FREEZE: True
  RESNETS:
    DEPTH: 101
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
    FREEZE: True
  ROI_HEADS:
    NUM_CLASSES: 6
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.75
    FREEZE_FEAT: True
  TRAIN_GCN: True
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('3vt_trainval_base2', )
  TEST: ('3vt_test_base2',)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  STEPS: (300,)
  MAX_ITER: 1600
  CHECKPOINT_PERIOD: 20000000
  WARMUP_ITERS: 100
OUTPUT_DIR: "/Path/to/Output/Dir"