_BASE_: "../../Base-RCNN.yaml"
MODEL:
  WEIGHTS: "/Path/to/Base/Pretrain/Weight"
  MASK_ON: False
  BACKBONE:
    FREEZE: True
  RESNETS:
    DEPTH: 101
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
    FREEZE: True
  ROI_HEADS:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.001
    NUM_CLASSES: 9
    FREEZE_FEAT: True
    CLS_DROPOUT: True
  TRAIN_GCN: True
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ("4ch_gcn_trainval_allx_1shot_seedx", )
  TEST: ('4ch_test_allx',)
SOLVER:
  # IMS_PER_BATCH: 16
  # BASE_LR: 0.005
  # STEPS: (800, )
  # MAX_ITER: 1000
  IMS_PER_BATCH: 8
  BASE_LR: 0.005
  STEPS: (1600, )
  MAX_ITER: 2000
  CHECKPOINT_PERIOD: 100000
  WARMUP_ITERS: 0
TEST:
  EVAL_PERIOD: 200
  PCB_ENABLE: False
  PCB_MODELPATH: "/Path/to/ImageNet/Pre-Train/Weight"
OUTPUT_DIR: "/Path/to/Output/Dir"